#!/bin/bash

START="\033"
END="m"
RESET="$START[0$END"

GREY_BLACK="$START[1;30$END"
GREY_BLACK_U="$START[1;4;30$END"
LIGHT_RED="$START[1;31$END"
DARK_RED="$START[1;31$END"
DARK_RED_U="$START[1;4;31$END"
LIGHT_GREEN="$START[0;32$END"
DARK_GREEN="$START[1;32$END"
DARK_GREEN_U="$START[1;4;32$END"
LIGHT_YELLOW="$START[0;33$END"
DARK_YELLOW="$START[1;33$END"
DARK_YELLOW_U="$START[1;4;33$END"
LIGHT_BLUE="$START[1;34$END"
DARK_BLUE="$START[1;34$END"
DARK_BLUE_U="$START[1;4;34$END"
LIGHT_MAGENTA="$START[0;35$END"
DARK_MAGENTA="$START[1;35$END"
DARK_MAGENTA_U="$START[1;4;35$END"
LIGHT_CYAN="$START[0;36$END"
DARK_CYAN="$START[1;36$END"
DARK_CYAN_U="$START[1;4;36$END"
LIGHT_WHITE="$START[0;37$END"
DARK_WHITE="$START[1;37$END"
DARK_WHITE_U="$START[1;4;37$END"

#echo -e "$GREY_BLACK Dark Gray  $RESET"
#echo -e "$GREY_BLACK_U Dark Gray Underlined  $RESET"
#echo -e "$LIGHT_RED Light Red $RESET"
#echo -e "$DARK_RED Dark Red $RESET"
#echo -e "$DARK_RED_U Dark Red Underlined $RESET"
#echo -e "$LIGHT_GREEN Light Green $RESET"
#echo -e "$DARK_GREEN Dark Green $RESET"
#echo -e "$DARK_GREEN_U Dark Green Underlined $RESET"
#echo -e "$LIGHT_YELLOW Light Yellow $RESET"
#echo -e "$DARK_YELLOW Dark Yellow $RESET"
#echo -e "$DARK_YELLOW_U Dark Yellow Underlined $RESET"
#echo -e "$LIGHT_BLUE Light Blue $RESET"
#echo -e "$DARK_BLUE Dark Blue $RESET"
#echo -e "$DARK_BLUE_U Dark Blue Underlined $RESET"
#echo -e "$LIGHT_MAGENTA Light Magenta $RESET"
#echo -e "$DARK_MAGENTA Dark Magenta $RESET"
#echo -e "$DARK_MAGENTA_U Dark Magenta Underlined $RESET"
#echo -e "$LIGHT_CYAN Light Cyan $RESET"
#echo -e "$DARK_CYAN Dark Cyan $RESET"
#echo -e "$DARK_CYAN_U Dark Cyan Underlined $RESET"
#echo -e "$LIGHT_WHITE Light White $RESET"
#echo -e "$DARK_WHITE Dark White $RESET"
#echo -e "$DARK_WHITE_U Dark White Underlined $RESET"
