---

# You can set any interface, that is listened by docker engine.
# e.g. docker_swarm_interface: "eth1"
docker_swarm_interface: "eth1"
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
#docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
# docker_swarm_addr: "{{ ansible_default_ipv4['address'] }}"
#docker_swarm_addr: "{{ ansible_eth1['ipv4'].address }}"
docker_swarm_port: 2377

# List of the users in the Docker group
docker_admin_users:
  - "{{ ansible_user | default(ansible_user_id) }}" # if ansible_user is not defined, we default to the ansible ansible_user_id fact

public_interface: eth0




