#- name: Create database
#  become: true
#  become_user: "{{ db_admin_user }}"
#  postgresql_db: name='{{ item }}' encoding='UTF-8' lc_collate='en_US.UTF-8'  lc_ctype='en_US.UTF-8' template='template0' state=present
#  with_items: "{{ db_names }}"

- name: Create database user and set privileges
  become: true
  become_user: "{{ db_admin_user }}"
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,LOGIN,NOREPLICATION,NOCREATEROLE,INHERIT
    state: present

- name: Setting db admin password
  become: true
  become_user: "{{ db_admin_user }}"
  shell: psql -c "ALTER USER {{ db_admin_user }} WITH PASSWORD '{{ db_admin_password }}';"

