- name: Adding APT repository key
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add PostgreSQL official APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"

- name: Install PostgreSQL and dependencies for the Ansible module
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - postgresql-9.5
    - python-psycopg2

- name: Track down postgres home
  shell: grep postgres /etc/passwd |  cut -d":" -f6
  register: postgres_home

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

