  - name: Start Swarm head node
    ec2:
      region: "{{ aws_region }}"
      image: "{{ swarm_template }}"
      instance_type: "{{ swarm_instance_type }}"
      key_name: "{{ ssh_key }}"
      group: "{{ swarm_security_group_name }}"
      user_data: "{{ lookup('template', '../templates/swarm-head.j2') }}"
      wait: yes
    register: swarm_head
 
  - debug: msg='Swarm head IP is {{ item.public_ip }}'
    with_items: swarm_head.instances

  - debug: msg='Swarm head IP is {{ item.private_ip }}'
    with_items: swarm_head.instances

  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname=swarm
    with_items: swarm_head.instances

  - name: Start Swarm nodes
    ec2:
      region: "{{ aws_region }}"
      image: "{{ swarm_template }}"
      instance_type: "{{ swarm_instance_type }}"
      key_name: "{{ ssh_key }}"
      group: "{{ swarm_security_group_name }}"
      user_data: "{{ lookup('template', '../templates/swarm-node.j2') }}"
      count: "{{ swarm_num_nodes }}"
      wait: yes
    register: ec2

  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname=swarm
    with_items: ec2.instances

  - name: Add new instance to host group
    add_host: hostname={{ item.public_ip }} groupname=swarm_nodes
    with_items: ec2.instances
