---

- name: Deploy Nginx Service.
  include: ../../docker-service/tasks/tasks-docker-service.yml
  vars:
    service_name: nginx-web-rproxy
    #repo: git@bitbucket.org:fonhivr/nginx-web-rproxy.git
    path: "source"
    version: HEAD
    ports:
      - "80:80"
    networks:
      - "{{ global_network }}"

