---
- name: Check if network {{ name }} exists
  delegate_to: "{{ groups['docker_swarm_issuer'][0] }}"
  run_once: true
  command: docker network ls -q --filter name=^{{ name }}$
  register: network_exists
  changed_when: false

- name: Create network {{ name }}
  command: docker network create --driver {{ driver }} {{ name }}
  when: network_exists.stdout == ""
  delegate_to: "{{ groups['docker_swarm_issuer'][0] }}"
  run_once: true

