#!/usr/bin/env ansible-playbook
---
- hosts: docker_swarm_issuer
  roles:
    - { role: docker-network ,name: "{{ global_network }}" , driver: overlay }
    - docker-registry
    - nginx-web-rproxy
    - activemq
