---
- hosts: all

  roles:
    - { role: oracle-java8, tags: ['java'] }
    - { role: createdb, tags: ['db'] }
    - { role: tomcat, tags: ['tomcat'] }
    - { role: artifacts, tags: ['artifact']}
    - { role: solr, tags: ['solr']}
    - { role: activemq, tags: ['activemq']}

  tasks:
    - name: Install Package
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
#       - jq                            #jq
#       - autossh                       #autossh
        - mercurial                     #mercurial
#       - ansible                       #ansible
#       - maven                         #maven
        - git                           #git
      tags:
        - packages


    - name: ensure github.com is a known host
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"
      tags:
        - cvs


    - name: ensure bitbucket.org is a known host
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
        regexp: "^bitbucket\\.org"
      tags:
        - cvs


    - name: Git checkout
      git:
        repo: git@bitbucket.org:fonhivr/human-ivr-brain.git
        dest: "{{ ansible_user_dir }}/human-ivr-brain"
        update: no
      tags:
        - cvs








