---

- name: Prerequisites packages are installed
  apt: name={{ item }} state=installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-setuptools # for easy_install
  when: ansible_os_family == 'Debian'


# Variables setup
- name: Include os-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Makes sure that the repo cache is fresh
- name: Update APT cache
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'
  changed_when: false

- name: pip is up to date
  easy_install:
    name: pip

# with_indexed_items is required as a workaround for this issue:
# https://github.com/ansible/ansible-modules-core/issues/1178
#- name: Install python-pip.
#  package:
#    name: "{{ item.1 }}"
#    state: present
#  with_indexed_items: "{{ python_pip_packages }}"
#  when: ansible_os_family == 'Debian'
#    and ansible_python_version | version_compare('2.6.0', '>=')
#    and ansible_python_version | version_compare('2.7.9', '<')

- name: Install the Python SNI support packages.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_sni_support_packages }}"
  when: ansible_os_family == 'Debian'
    and ansible_python_version | version_compare('2.6.0', '>=')
    and ansible_python_version | version_compare('2.7.9', '<')

# There extra pip dependencies are needed to add SSL SNI support to
# Python version prior to 2.7.9. SNI support is needed by the Ansible
# apt_key module.
- name: Install the Python SNI python-pip dependencies.
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_sni_pip_dependencies }}"
  when: ansible_os_family == 'Debian'
    and ansible_python_version | version_compare('2.6.0', '>=')
    and ansible_python_version | version_compare('2.7.9', '<')
